Repository Polidea/cmake-nRF5x, pull requests merged in 2020-06, with the labels that each got.

#15 Exclude 'micro-ecc-src' target from 'all'
  cmake/nrf5_external_libs.cmake
Labels: bug

#17 Pass log level to CI build scripts
  ci/scripts/build_all_examples.sh
  ci/scripts/build_example.sh
  ci/scripts/common/build_example.sh
  ci/scripts/common/consts.sh
Labels: enhancement

#18 Summary report for 'Build all examples' CI script
  ci/scripts/build_all_examples.sh
  ci/scripts/common/consts.sh
Labels: enhancement

#19 Filters for 'Build all examples' CI script
  ci/README.md
  ci/scripts/build_all_examples.sh
Labels: enhancement

#20 Clean before building examples on CI
  ci/scripts/build_all_examples.sh
  ci/scripts/build_example.sh
  ci/scripts/common/build_example.sh
Labels: enhancement

#22 Add support for groups creation.
  ci/scripts/common/consts.sh
  ci/scripts/generate_cmake.sh
  ci/scripts/python/generate_cmake.py
  ci/scripts/python/generate_cmake_tests.py
  ci/scripts/python/nrf5_cmake/library_description.py
  ci/scripts/python/nrf5_cmake/library_operations.py
  ci/scripts/python/nrf5_cmake/version.py
  ci/templates/cmake_groups.j2
  cmake/nrf5.cmake
  cmake/nrf5_groups.cmake
Labels: enhancement

#21 Support for more examples, drivers and libraries (1)
  .github/workflows/.github-ci.yml
  ci/examples/peripheral/cli/CMakeLists.txt
  ci/examples/peripheral/nrfx_spim/CMakeLists.txt
  ci/examples/peripheral/spi/CMakeLists.txt
  ci/examples/peripheral/spi_master_using_nrf_spi_mngr/CMakeLists.txt
  ci/examples/peripheral/spis/CMakeLists.txt
  ci/examples/peripheral/twi_master_using_nrf_twi_mngr/CMakeLists.txt
  ci/examples/peripheral/twi_scanner/CMakeLists.txt
  ci/examples/peripheral/twi_sensor/CMakeLists.txt
  ci/examples/peripheral/uart/CMakeLists.txt
  ci/examples/peripheral/usbd/CMakeLists.txt
  ci/examples/peripheral/usbd_cdc_acm/CMakeLists.txt
  ci/libraries/nrf5_bsp.json
  ci/libraries/nrf5_common.json
  ci/libraries/nrf5_external.json
  ci/libraries/nrf5_log.json
  ci/libraries/nrf5_misc.json
  ci/libraries/nrf5_nrfx.json
  ci/libraries/nrf5_usbd.json
  cmake/nrf5.cmake
  cmake/nrf5_bsp.cmake
  cmake/nrf5_common.cmake
  cmake/nrf5_external.cmake
  cmake/nrf5_log.cmake
  cmake/nrf5_misc.cmake
  cmake/nrf5_nrfx.cmake
  cmake/nrf5_usbd.cmake
Labels: enhancement

#23 Support for 'blank' and 'mbr' configurations
  ci/scripts/build_all_examples.sh
  cmake/nrf5.cmake
  cmake/nrf5_validate.cmake
Labels: enhancement

#44 Add utility script to generate example based on the Makefile contents
  ci/README.md
  ci/scripts/README.md
  ci/scripts/common/consts.sh
  ci/scripts/generate_example.sh
  ci/scripts/python/check_coverage.py
  ci/scripts/python/generate_example.py
  ci/scripts/python/scrape_makefiles.py
  ci/templates/cmake_example.j2
Labels: ci

#55 Moved legacy driver definitions to nrf5_drv.json
  ci/libraries/nrf5_drv.json
  ci/libraries/nrf5_nrfx.json
  cmake/nrf5.cmake
  cmake/nrf5_drv.cmake
  cmake/nrf5_nrfx.cmake
Labels: cleanup, help wanted

#54 Display a warning when the user does not specify a linker script
  cmake/nrf5.cmake
Labels: enhancement, help wanted

#53 Allow to specify J-Link serial number nrfjprog to use
  README.md
  cmake/nrf5.cmake
Labels: enhancement

#52 Add `nrf5_bsp_defs` lib with BSP-related definitions
  ci/examples/peripheral/fatfs/CMakeLists.txt
  ci/examples/peripheral/pwm_library/CMakeLists.txt
  ci/examples/peripheral/qdec/CMakeLists.txt
  ci/examples/peripheral/temperature/CMakeLists.txt
  ci/examples/peripheral/timer/CMakeLists.txt
  ci/examples/peripheral/uart/CMakeLists.txt
  ci/libraries/nrf5_bsp.json
  cmake/nrf5_bsp.cmake
Labels: enhancement, help wanted
